url: http://192.168.56.1:5000
baseurl: 

# Site settings
title: Interjera un Arhitektūras Pakalpojumi
email: ilze.desaine@gmail.com
description: "Interjerdizaina un Arhitektūras Pakalpojumi, Dizainere Ilze Desaine"


# Team names, titles and social links
people:
- name: Ilze Desaine
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/ilze_desaine/
  - title: facebook
    url: https://www.facebook.com/idinterior.lv/

# Postal address (add as many lines as necessary)
address:
  - line: Rīga
  - line: Latvija

# Build settings
markdown: kramdown
permalink: pretty

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jekyll-assets